sudo: required

language: csharp

cache:
  directories:
    - packages

services:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_1fc90f464345_key -iv $encrypted_1fc90f464345_iv -in dockerKey.enc -out dockerKey -d
  - eval "$(ssh-agent -s)"
  - chmod 600 dockerKey
  - ssh-add dockerKey
  - docker build -t webapp:test -f ./dockerfile/test .

script:
  - docker run -it --rm -v $PWD/publish:/root/publish -v $PWD/packages:/root/.nuget/packages webapp:test
  
after_success:
  - docker build -t webapp:release -f ./dockerfile/release .
  - docker run -it --rm -p 8080:5000 webapp:release