sudo: required

language: csharp

cache:
  directories:
    - packages

services:
  - docker

before_install:
  - docker build -t webapp:test -f ./dockerfile/test .

script:
  - docker run -it --rm -v $PWD/publish:/root/publish -v $PWD/packages:/root/.nuget/packages webapp:test
  
after_success:
  - docker build -t webapp:release -f ./dockerfile/release .
  - docker run -it --rm -p 8080:5000 webapp:release